export enum Environment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}

export enum EnvField {
  NODE_ENV = 'NODE_ENV',
  SERVER_PREFIX = 'SERVER_PREFIX',
  SERVER_PORT = 'SERVER_PORT',
  SERVER_EXTERNAL_URL = 'SERVER_EXTERNAL_URL',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DEBUG = 'DB_DEBUG',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
}
